### ISSUE TITLE
I cant get it working with riva tuner

### ISSUE THREAD

**Issue by Obazzi** [Jagailo/YetAnotherKeyDisplayer#11]
I have RivaTuner and YAKD running with the right setting enabled and it does not show anything in game. I tried restarting both programs multiple times, but no use. Furthermore, I know it is supposed to work because when I open MSI Afterburner it shows the all of my performance metrics in game, so it is not a problem with RivaTuner and the game but with RivaTuner and YAKD.

**Comment by Jagailo** [comment]
Hello, could you please provide what versions of programs you are using.

- MSI Afterburner
- Guru3D RTSS Rivatuner Statistics Server
- YAKD

What games have you tried? Full screen or window mode?

**Comment by Obazzi** [comment]
## Versions
Afterburner: 4.6.3
RivaTuner: 7.3.0
YAKD: 1.2.1

## Games
Games I tried with YAKD and RivaTuner open:

- Team Fortress 2
- A Story About My Uncle
- DOOM 2016

All of them show the built-in RivaTuner FPS counter correctly, but I do not see any of my key presses. Also, when I start Afterburner, it displays the advanced information on screen. All the games were tried in full screen, but after I saw your message I tried A Story About My Uncle in windowed mode, and it still does not show my key presses but shows RivaTuner just fine.

## Settings
Don't let my custom theme fool you, I am running **Windows 10 Enterprise 2016 LTSB 64-bit** witch is equivalent to **Windows 10 Enterprise Ver. 1607 64-bit**.
![image](https://user-images.githubusercontent.com/88412380/135548875-cd9a39fa-451b-4223-aa61-4f3f85bc1cf6.png)

**Comment by Obazzi** [comment]
I forgot to mention it, but the YAKD window option works flawlessly, and I can see all of my keyboard and mouse presses.

**Comment by Jagailo** [comment]
I was unable to reproduce your problem. But I also have newer versions of programs.
Update RTSS to 7.3.2 Beta 5 ([here](https://www.guru3d.com/files-details/rtss-rivatuner-statistics-server-download.html))
Also try the beta version of MSI Afterburner 4.6.4
![image](https://user-images.githubusercontent.com/10468120/135761922-d26bb75b-bc51-4ee0-b9a2-4ffb5d18724f.png)

Try the following steps:

1. Launch YAKD;
2. Select the RTSS mode;
3. Make sure that RTSS has started (tray icon);
4. Start MSI Afterburner.

Should work.

[Watch the video demo](https://youtu.be/2rZRXMGnBDA)

**Comment by r3sus** [comment]
Hi. 
I do have the same issue. 
Tested on Dead Space 1 (DS1).
Both windowed and full-screen. 
Latest RTSS 733. 
Not using MSI AB. 
Windows 7. 

I assume that it might be caused by the way game hooks keyboard - it's like swallows input: 
It uses SetWindowsHookEx, but not sure it's endpoint, it might also use directx hooks. 
I had the same issues with NohBoard (separate window), and some others, which work fine with Lone Survivor i.e. (non DX game).

I'm also using this RTSS plugin _
https://github.com/hallcristobal/LiveSplit.RivaTuner
_ which draws geometry as required. 
(requires LiveSplit + add RivaTuner in layout)
Tested without it, so that's not compatibility issue. 

Other OSD that worked with DS1:
OBS plugin: https://github.com/univrsal/input-overlay
AHK script (separate window): https://www.dcmembers.com/skrommel/download/showoff/

P.S. Thanks a lot for great project!

**Comment by scumware** [comment]
I had reproduced this bug.
If RTSS started befor YAKD or RTSS started befor clicking RTSSRadioButton then RTSSHandler._osd will not initialized and _osd?.Update(text); does nothing.

**Comment by Jagailo** [comment]
If anyone else encounters this problem, try to use YAKD 1.4 and the latest stable version of RTSS.
