### ISSUE TITLE
Maybe a delay

### ISSUE THREAD

**Issue by martinycoartist** [Jagailo/YetAnotherKeyDisplayer#6]
Hi,
I'm streamer
And I found your application very useful
I was wondering if there is any option to add a delay
so the keys I press stay on screen for a second or less.
Greetings and good work

**Comment by Jagailo** [comment]
Hi, thanks you for feedback
I'll try to play with a delay
And if I'm satisfied with the result, it may appear

**Comment by Jagailo** [comment]
Hi @martinycoartist,
Unfortunately, the logic of the output buttons is implemented as simple as possible, since I didn't think about the possibility of any delay. This functionality cannot be implemented without redoing the entire system. Honestly, I have neither the time nor the desire to do this.

Stay safe and all the best.
